In [10]:
import numpy as np
x=23
y=23
name="Umar"


<h1>Method 1<h1>

In [3]:
print ("My name is :{name} and the sum of {x} and {y} is {c}".format(name=name,x=x,y=y,c=x+y))


My name is :Umar and the sum of 23 and 23 is 46


<h1>Method 2 </h1>


In [4]:
print ("My name is {} and the sum of {} and {} is {}".format(name,x,y,x+y))

My name is Umar and the sum of 23 and 23 is 46


<h1>Method 3</h1>

In [5]:
print ("My name is "+ name + "and the sum of "+str(x)+ " and "+str(y)+ " is "+str(x+y))

My name is Umarand the sum of 23 and 23 is 46


<h1>Method 4</h1>

In [6]:
string = "My name is %s and the sum of %d and %d is %d"%(name,x,y,x+y)
print(string)

My name is Umar and the sum of 23 and 23 is 46


<h1>Input Pratice</h1>

In [7]:
name = input("Enter your name:")


Enter your name:ef


In [8]:
age = int(input("Enter your age:"))

Enter your age:df


ValueError: invalid literal for int() with base 10: 'df'

In [ ]:
print ("User name is {} and age is {}".format(name,age))

<h1> List Pratice</h1>


In [ ]:
name = ["Umar","Ali","Momina","Faiz"]
name

In [ ]:
name.append("Semi")


In [ ]:
print(name)
name.pop()

In [ ]:
print (name)

<h1>Dict Pratice</h1>

In [ ]:
my_name = {"Umar":12,"Ali":23,"Momina":34}

In [ ]:
my_name.keys()

In [ ]:
my_name.values()

In [ ]:
my_name.items()

In [11]:
a = np.arange(4).reshape(2 , 2)
b = np.arange(4,8).reshape(2,2)
c = np.arange(9,13).reshape(2,2)
np.vstack((a, b,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 9, 10],
       [11, 12]])

In [12]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.sum(x)

21

In [13]:
x = np.array([[1, 2],[3, 4]]) 
y = np.array([[5, 6],[7, 8]])
x+y

array([[ 6,  8],
       [10, 12]])

In [22]:
a = np.array([[3,3,0,3,3]])
a.ndim

2

In [23]:
b = np.full((3, 2), 7)
b.flatten()

array([7, 7, 7, 7, 7, 7])

In [24]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[1][2]

7